flowchart TD

A[Projects Dashboard] --> B[Add New Building]
A --> C[Open / Edit Building]
A --> E[Delete Building Popup]
A --> H[User Profile]

B --> C

C --> SRI1[SRI View 1 Methodology Selection]
C --> EPB1[EPB View 1 Calculation Settings]

EPB1 --> EPB1B[EPB View 1b Climate Data]
EPB1B --> EPB2[EPB View 2 Building Envelope]
EPB2 --> EPB3[EPB View 3 Thermal Zone]
EPB3 --> EPBSPACES[EPB Spaces Tab]
EPBSPACES --> EPBOPS[EPB Operations Tab]
EPBOPS --> EPB4[EPB Results Performance Summary]

SRI1 -->|Default weightings| SRI2[SRI Decision Default Weightings]
SRI1 -->|Weighting settings| SRI3[SRI View 2 Weighting Settings]
SRI2 -->|Continue| SRI14[SRI14 Results]
SRI3 -->|Continue| SRI14

SRI14 --> SRI5[Heating Tab]
SRI14 --> SRI6[DHW Tab]
SRI14 --> SRI7[Cooling Tab]
SRI14 --> SRI8[Ventilation Tab]
SRI14 --> SRI9[Lighting Tab]
SRI14 --> SRI10[Dynamic Envelope Tab]
SRI14 --> SRI11[Electricity Tab]
SRI14 --> SRI12[EV Charging Tab]
SRI14 --> SRI13[Monitoring & Control Tab]

SRI5 --> SRI14[SRI View 3 Results]
SRI6 --> SRI14[SRI View 3 Results]
SRI7 --> SRI14[SRI View 3 Results]
SRI8 --> SRI14[SRI View 3 Results]
SRI9 --> SRI14[SRI View 3 Results]
SRI10 --> SRI14[SRI View 3 Results]
SRI11 --> SRI14[SRI View 3 Results]
SRI12 --> SRI14[SRI View 3 Results]
SRI13 --> SRI14[SRI View 3 Results]